src/generated-sources/java/com/jspxcms/ext/domain/QAd.java
package com.jspxcms.ext.domain;

import static com.querydsl.core.types.PathMetadataFactory.*;

import com.querydsl.core.types.dsl.*;

import com.querydsl.core.types.PathMetadata;
import javax.annotation.Generated;
import com.querydsl.core.types.Path;
import com.querydsl.core.types.dsl.PathInits;


/**
 * QAd is a Querydsl query type for Ad
 */
@Generated("com.querydsl.codegen.EntitySerializer")
public class QAd extends EntityPathBase<Ad> {

    private static final long serialVersionUID = -211983203L;

    private static final PathInits INITS = PathInits.DIRECT2;

    public static final QAd ad = new QAd("ad");

    public final DateTimePath<java.util.Date> beginDate = createDateTime("beginDate", java.util.Date.class);

    public final DateTimePath<java.util.Date> endDate = createDateTime("endDate", java.util.Date.class);

    public final StringPath flash = createString("flash");

    public final NumberPath<Integer> id = createNumber("id", Integer.class);

    public final StringPath image = createString("image");

    public final StringPath name = createString("name");

    public final StringPath script = createString("script");

    public final NumberPath<Integer> seq = createNumber("seq", Integer.class);

    public final com.jspxcms.core.domain.QSite site;

    public final QAdSlot slot;

    public final StringPath text = createString("text");

    public final StringPath url = createString("url");

    public QAd(String variable) {
        this(Ad.class, forVariable(variable), INITS);
    }

    public QAd(Path<? extends Ad> path) {
        this(path.getType(), path.getMetadata(), PathInits.getFor(path.getMetadata(), INITS));
    }

    public QAd(PathMetadata metadata) {
        this(metadata, PathInits.getFor(metadata, INITS));
    }

    public QAd(PathMetadata metadata, PathInits inits) {
        this(Ad.class, metadata, inits);
    }

    public QAd(Class<? extends Ad> type, PathMetadata metadata, PathInits inits) {
        super(type, metadata, inits);
        this.site = inits.isInitialized("site") ? new com.jspxcms.core.domain.QSite(forProperty("site"), inits.get("site")) : null;
        this.slot = inits.isInitialized("slot") ? new QAdSlot(forProperty("slot"), inits.get("slot")) : null;
    }

}

src/generated-sources/java/com/jspxcms/ext/domain/QAdSlot.java
package com.jspxcms.ext.domain;

import static com.querydsl.core.types.PathMetadataFactory.*;

import com.querydsl.core.types.dsl.*;

import com.querydsl.core.types.PathMetadata;
import javax.annotation.Generated;
import com.querydsl.core.types.Path;
import com.querydsl.core.types.dsl.PathInits;


/**
 * QAdSlot is a Querydsl query type for AdSlot
 */
@Generated("com.querydsl.codegen.EntitySerializer")
public class QAdSlot extends EntityPathBase<AdSlot> {

    private static final long serialVersionUID = -2032718789L;

    private static final PathInits INITS = PathInits.DIRECT2;

    public static final QAdSlot adSlot = new QAdSlot("adSlot");

    public final ListPath<Ad, QAd> ads = this.<Ad, QAd>createList("ads", Ad.class, QAd.class, PathInits.DIRECT2);

    public final StringPath description = createString("description");

    public final NumberPath<Integer> height = createNumber("height", Integer.class);

    public final NumberPath<Integer> id = createNumber("id", Integer.class);

    public final StringPath name = createString("name");

    public final StringPath number = createString("number");

    public final com.jspxcms.core.domain.QSite site;

    public final StringPath template = createString("template");

    public final NumberPath<Integer> type = createNumber("type", Integer.class);

    public final NumberPath<Integer> width = createNumber("width", Integer.class);

    public QAdSlot(String variable) {
        this(AdSlot.class, forVariable(variable), INITS);
    }

    public QAdSlot(Path<? extends AdSlot> path) {
        this(path.getType(), path.getMetadata(), PathInits.getFor(path.getMetadata(), INITS));
    }

    public QAdSlot(PathMetadata metadata) {
        this(metadata, PathInits.getFor(metadata, INITS));
    }

    public QAdSlot(PathMetadata metadata, PathInits inits) {
        this(AdSlot.class, metadata, inits);
    }

    public QAdSlot(Class<? extends AdSlot> type, PathMetadata metadata, PathInits inits) {
        super(type, metadata, inits);
        this.site = inits.isInitialized("site") ? new com.jspxcms.core.domain.QSite(forProperty("site"), inits.get("site")) : null;
    }

}

src/generated-sources/java/com/jspxcms/ext/domain/QCollect.java
package com.jspxcms.ext.domain;

import static com.querydsl.core.types.PathMetadataFactory.*;

import com.querydsl.core.types.dsl.*;

import com.querydsl.core.types.PathMetadata;
import javax.annotation.Generated;
import com.querydsl.core.types.Path;
import com.querydsl.core.types.dsl.PathInits;


/**
 * QCollect is a Querydsl query type for Collect
 */
@Generated("com.querydsl.codegen.EntitySerializer")
public class QCollect extends EntityPathBase<Collect> {

    private static final long serialVersionUID = -771734288L;

    private static final PathInits INITS = PathInits.DIRECT2;

    public static final QCollect collect = new QCollect("collect");

    public final BooleanPath allowDuplicate = createBoolean("allowDuplicate");

    public final StringPath blockAreaPattern = createString("blockAreaPattern");

    public final BooleanPath blockAreaReg = createBoolean("blockAreaReg");

    public final StringPath blockPattern = createString("blockPattern");

    public final BooleanPath blockReg = createBoolean("blockReg");

    public final StringPath charset = createString("charset");

    public final BooleanPath desc = createBoolean("desc");

    public final BooleanPath downloadImage = createBoolean("downloadImage");

    public final ListPath<CollectField, QCollectField> fields = this.<CollectField, QCollectField>createList("fields", CollectField.class, QCollectField.class, PathInits.DIRECT2);

    public final NumberPath<Integer> id = createNumber("id", Integer.class);

    public final NumberPath<Integer> intervalMax = createNumber("intervalMax", Integer.class);

    public final NumberPath<Integer> intervalMin = createNumber("intervalMin", Integer.class);

    public final StringPath itemAreaPattern = createString("itemAreaPattern");

    public final BooleanPath itemAreaReg = createBoolean("itemAreaReg");

    public final StringPath itemPattern = createString("itemPattern");

    public final BooleanPath itemReg = createBoolean("itemReg");

    public final StringPath listNextPattern = createString("listNextPattern");

    public final BooleanPath listNextReg = createBoolean("listNextReg");

    public final StringPath listPattern = createString("listPattern");

    public final StringPath name = createString("name");

    public final com.jspxcms.core.domain.QNode node;

    public final NumberPath<Integer> pageBegin = createNumber("pageBegin", Integer.class);

    public final NumberPath<Integer> pageEnd = createNumber("pageEnd", Integer.class);

    public final com.jspxcms.core.domain.QSite site;

    public final NumberPath<Integer> status = createNumber("status", Integer.class);

    public final BooleanPath submit = createBoolean("submit");

    public final com.jspxcms.core.domain.QUser user;

    public final StringPath userAgent = createString("userAgent");

    public QCollect(String variable) {
        this(Collect.class, forVariable(variable), INITS);
    }

    public QCollect(Path<? extends Collect> path) {
        this(path.getType(), path.getMetadata(), PathInits.getFor(path.getMetadata(), INITS));
    }

    public QCollect(PathMetadata metadata) {
        this(metadata, PathInits.getFor(metadata, INITS));
    }

    public QCollect(PathMetadata metadata, PathInits inits) {
        this(Collect.class, metadata, inits);
    }

    public QCollect(Class<? extends Collect> type, PathMetadata metadata, PathInits inits) {
        super(type, metadata, inits);
        this.node = inits.isInitialized("node") ? new com.jspxcms.core.domain.QNode(forProperty("node"), inits.get("node")) : null;
        this.site = inits.isInitialized("site") ? new com.jspxcms.core.domain.QSite(forProperty("site"), inits.get("site")) : null;
        this.user = inits.isInitialized("user") ? new com.jspxcms.core.domain.QUser(forProperty("user"), inits.get("user")) : null;
    }

}

src/generated-sources/java/com/jspxcms/ext/domain/QCollectField.java
package com.jspxcms.ext.domain;

import static com.querydsl.core.types.PathMetadataFactory.*;

import com.querydsl.core.types.dsl.*;

import com.querydsl.core.types.PathMetadata;
import javax.annotation.Generated;
import com.querydsl.core.types.Path;
import com.querydsl.core.types.dsl.PathInits;


/**
 * QCollectField is a Querydsl query type for CollectField
 */
@Generated("com.querydsl.codegen.EntitySerializer")
public class QCollectField extends EntityPathBase<CollectField> {

    private static final long serialVersionUID = 354484714L;

    private static final PathInits INITS = PathInits.DIRECT2;

    public static final QCollectField collectField = new QCollectField("collectField");

    public final StringPath code = createString("code");

    public final QCollect collect;

    public final StringPath dataAreaPattern = createString("dataAreaPattern");

    public final BooleanPath dataAreaReg = createBoolean("dataAreaReg");

    public final StringPath dataPattern = createString("dataPattern");

    public final BooleanPath dataReg = createBoolean("dataReg");

    public final StringPath dateFormat = createString("dateFormat");

    public final StringPath downloadType = createString("downloadType");

    public final StringPath filter = createString("filter");

    public final NumberPath<Integer> id = createNumber("id", Integer.class);

    public final StringPath imageParam = createString("imageParam");

    public final StringPath name = createString("name");

    public final NumberPath<Integer> seq = createNumber("seq", Integer.class);

    public final com.jspxcms.core.domain.QSite site;

    public final StringPath sourceText = createString("sourceText");

    public final NumberPath<Integer> sourceType = createNumber("sourceType", Integer.class);

    public final StringPath sourceUrl = createString("sourceUrl");

    public final NumberPath<Integer> type = createNumber("type", Integer.class);

    public QCollectField(String variable) {
        this(CollectField.class, forVariable(variable), INITS);
    }

    public QCollectField(Path<? extends CollectField> path) {
        this(path.getType(), path.getMetadata(), PathInits.getFor(path.getMetadata(), INITS));
    }

    public QCollectField(PathMetadata metadata) {
        this(metadata, PathInits.getFor(metadata, INITS));
    }

    public QCollectField(PathMetadata metadata, PathInits inits) {
        this(CollectField.class, metadata, inits);
    }

    public QCollectField(Class<? extends CollectField> type, PathMetadata metadata, PathInits inits) {
        super(type, metadata, inits);
        this.collect = inits.isInitialized("collect") ? new QCollect(forProperty("collect"), inits.get("collect")) : null;
        this.site = inits.isInitialized("site") ? new com.jspxcms.core.domain.QSite(forProperty("site"), inits.get("site")) : null;
    }

}

src/generated-sources/java/com/jspxcms/ext/domain/QFriendlink.java
package com.jspxcms.ext.domain;

import static com.querydsl.core.types.PathMetadataFactory.*;

import com.querydsl.core.types.dsl.*;

import com.querydsl.core.types.PathMetadata;
import javax.annotation.Generated;
import com.querydsl.core.types.Path;
import com.querydsl.core.types.dsl.PathInits;


/**
 * QFriendlink is a Querydsl query type for Friendlink
 */
@Generated("com.querydsl.codegen.EntitySerializer")
public class QFriendlink extends EntityPathBase<Friendlink> {

    private static final long serialVersionUID = 209222162L;

    private static final PathInits INITS = PathInits.DIRECT2;

    public static final QFriendlink friendlink = new QFriendlink("friendlink");

    public final StringPath description = createString("description");

    public final StringPath email = createString("email");

    public final NumberPath<Integer> id = createNumber("id", Integer.class);

    public final StringPath logo = createString("logo");

    public final StringPath name = createString("name");

    public final BooleanPath recommend = createBoolean("recommend");

    public final NumberPath<Integer> seq = createNumber("seq", Integer.class);

    public final com.jspxcms.core.domain.QSite site;

    public final NumberPath<Integer> status = createNumber("status", Integer.class);

    public final QFriendlinkType type;

    public final StringPath url = createString("url");

    public final BooleanPath withLogo = createBoolean("withLogo");

    public QFriendlink(String variable) {
        this(Friendlink.class, forVariable(variable), INITS);
    }

    public QFriendlink(Path<? extends Friendlink> path) {
        this(path.getType(), path.getMetadata(), PathInits.getFor(path.getMetadata(), INITS));
    }

    public QFriendlink(PathMetadata metadata) {
        this(metadata, PathInits.getFor(metadata, INITS));
    }

    public QFriendlink(PathMetadata metadata, PathInits inits) {
        this(Friendlink.class, metadata, inits);
    }

    public QFriendlink(Class<? extends Friendlink> type, PathMetadata metadata, PathInits inits) {
        super(type, metadata, inits);
        this.site = inits.isInitialized("site") ? new com.jspxcms.core.domain.QSite(forProperty("site"), inits.get("site")) : null;
        this.type = inits.isInitialized("type") ? new QFriendlinkType(forProperty("type"), inits.get("type")) : null;
    }

}

src/generated-sources/java/com/jspxcms/ext/domain/QFriendlinkType.java
package com.jspxcms.ext.domain;

import static com.querydsl.core.types.PathMetadataFactory.*;

import com.querydsl.core.types.dsl.*;

import com.querydsl.core.types.PathMetadata;
import javax.annotation.Generated;
import com.querydsl.core.types.Path;
import com.querydsl.core.types.dsl.PathInits;


/**
 * QFriendlinkType is a Querydsl query type for FriendlinkType
 */
@Generated("com.querydsl.codegen.EntitySerializer")
public class QFriendlinkType extends EntityPathBase<FriendlinkType> {

    private static final long serialVersionUID = -925817748L;

    private static final PathInits INITS = PathInits.DIRECT2;

    public static final QFriendlinkType friendlinkType = new QFriendlinkType("friendlinkType");

    public final NumberPath<Integer> id = createNumber("id", Integer.class);

    public final StringPath name = createString("name");

    public final StringPath number = createString("number");

    public final NumberPath<Integer> seq = createNumber("seq", Integer.class);

    public final com.jspxcms.core.domain.QSite site;

    public QFriendlinkType(String variable) {
        this(FriendlinkType.class, forVariable(variable), INITS);
    }

    public QFriendlinkType(Path<? extends FriendlinkType> path) {
        this(path.getType(), path.getMetadata(), PathInits.getFor(path.getMetadata(), INITS));
    }

    public QFriendlinkType(PathMetadata metadata) {
        this(metadata, PathInits.getFor(metadata, INITS));
    }

    public QFriendlinkType(PathMetadata metadata, PathInits inits) {
        this(FriendlinkType.class, metadata, inits);
    }

    public QFriendlinkType(Class<? extends FriendlinkType> type, PathMetadata metadata, PathInits inits) {
        super(type, metadata, inits);
        this.site = inits.isInitialized("site") ? new com.jspxcms.core.domain.QSite(forProperty("site"), inits.get("site")) : null;
    }

}

src/main/java/com/jspxcms/core/domain/InfoFile.java
package com.jspxcms.core.domain;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Transient;

import org.apache.commons.io.FilenameUtils;

import com.jspxcms.common.file.FilesEx;

/**
 * InfoFile
 * 
 * @author liufang
 * 
 */
@Embeddable
public class InfoFile implements Serializable {
	private static final long serialVersionUID = 1L;

	public InfoFile() {
	}

	public InfoFile(String name, String file, Long length) {
		this.name = name;
		this.file = file;
		this.length = length;
		this.downloads = 0;
	}

	@Transient
	public String getSize() {
		Long length = getLength();
		return FilesEx.getSize(length);
	}

	@Transient
	public String getExtension() {
		return FilenameUtils.getExtension(getName());
	}

	private String name;
	private Long length;

	private String file;
	private Integer downloads;

	@Column(name = "f_name", nullable = false, length = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "f_length", nullable = false)
	public Long getLength() {
		return length;
	}

	public void setLength(Long length) {
		this.length = length;
	}

	@Column(name = "f_file", nullable = false)
	public String getFile() {
		return this.file;
	}

	public void setFile(String file) {
		this.file = file;
	}

	@Column(name = "f_downloads", nullable = false)
	public Integer getDownloads() {
		return this.downloads;
	}

	public void setDownloads(Integer downloads) {
		this.downloads = downloads;
	}
}

src/main/webapp/WEB-INF/views/ext/guestbook/guestbook_list.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@ taglib prefix="fnx" uri="http://java.sun.com/jsp/jstl/functionsx"%>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="f" uri="http://www.jspxcms.com/tags/form"%>
<%@ taglib prefix="shiro" uri="http://shiro.apache.org/tags"%>
<%@ taglib prefix="tags" tagdir="/WEB-INF/tags"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>Jspxcms管理平台 - Powered by Jspxcms</title>
<jsp:include page="/WEB-INF/views/commons/head.jsp"></jsp:include>
<script type="text/javascript">
$(function() {
	$("#pagedTable").tableHighlight();
	$("#sortHead").headSort();
});
function confirmDelete() {
	return confirm("<s:message code='confirmDelete'/>");
}
function optSingle(opt) {
	if(Cms.checkeds("ids")==0) {
		alert("<s:message code='pleaseSelectRecord'/>");
		return false;
	}
	if(Cms.checkeds("ids")>1) {
		alert("<s:message code='pleaseSelectOne'/>");
		return false;
	}
	var id = $("input[name='ids']:checkbox:checked").val();
	location.href=$(opt+id).attr("href");
}
function optDelete(form) {
	if(Cms.checkeds("ids")==0) {
		alert("<s:message code='pleaseSelectRecord'/>");
		return false;
	}
	if(!confirmDelete()) {
		return false;
	}
	form.action='delete.do';
	form.submit();
	return true;
}
</script>
</head>
<body class="c-body">
<jsp:include page="/WEB-INF/views/commons/show_message.jsp"/>
<div class="c-bar margin-top5">
  <span class="c-position"><s:message code="guestbook.management"/> - <s:message code="list"/></span>
	<span class="c-total">(<s:message code="totalElements" arguments="${fn:length(pagedList.content)}"/>)</span>
</div>
<form action="list.do" method="get">
	<fieldset class="c-fieldset">
    <legend><s:message code="search"/></legend>
	  <label class="c-lab">
	  	<s:message code="guestbook.type"/>:
	  	<select name="search_EQ_type.id">
	  		<option value=""><s:message code="allSelect"/></option>
	  		<f:options items="${typeList}" itemValue="id" itemLabel="name" selected="${requestScope['search_EQ_type.id'][0]}"/>
	  	</select>
	  </label>
	  <label class="c-lab">
	  	<s:message code="guestbook.recommend"/>:
	  	<select name="search_EQ_recommend_Boolean">
	  		<option value=""><s:message code="allSelect"/></option>
	  		<f:option value="true" selected="${search_EQ_recommend_Boolean[0]}"><s:message code="yes"/></f:option>
	  		<f:option value="false" selected="${search_EQ_recommend_Boolean[0]}"><s:message code="no"/></f:option>
	  	</select>
	  </label>
	  <label class="c-lab"><s:message code="guestbook.status"/>:
	  	<select name="search_EQ_status">
          <option value=""><s:message code="allSelect"/></option>
	      <option value="0"<c:if test="${'0' eq search_EQ_status[0]}"> selected="selected"</c:if>><s:message code="guestbook.status.0"/></option>
	      <option value="1"<c:if test="${'1' eq search_EQ_status[0]}"> selected="selected"</c:if>><s:message code="guestbook.status.1"/></option>
	      <option value="2"<c:if test="${'2' eq search_EQ_status[0]}"> selected="selected"</c:if>><s:message code="guestbook.status.2"/></option>
        </select>
	  </label>
	  <label class="c-lab">
	  	<s:message code="guestbook.reply"/>:
	  	<select name="search_EQ_reply_Boolean">
	  		<option value=""><s:message code="allSelect"/></option>
	  		<f:option value="true" selected="${search_EQ_reply_Boolean[0]}"><s:message code="yes"/></f:option>
	  		<f:option value="false" selected="${search_EQ_reply_Boolean[0]}"><s:message code="no"/></f:option>
	  	</select>
	  </label>
	  <label class="c-lab"><input type="submit" value="<s:message code="search"/>"/></label>
  </fieldset>
</form>
<form method="post">
<tags:search_params/>
<div class="ls-bc-opt">
	<shiro:hasPermission name="ext:guestbook:create">
	<div class="ls-btn"><input type="button" value="<s:message code="create"/>" onclick="location.href='create.do?${searchstring}';"/></div>
  <div class="ls-btn"></div>
  </shiro:hasPermission>
	<shiro:hasPermission name="ext:guestbook:copy">
  <div class="ls-btn"><input type="button" value="<s:message code="copy"/>" onclick="return optSingle('#copy_opt_');"/></div>
  </shiro:hasPermission>
	<shiro:hasPermission name="ext:guestbook:edit">
  <div class="ls-btn"><input type="button" value="<s:message code="edit"/>" onclick="return optSingle('#edit_opt_');"/></div>
  </shiro:hasPermission>
	<shiro:hasPermission name="ext:guestbook:delete">
  <div class="ls-btn"><input type="button" value="<s:message code="delete"/>" onclick="return optDelete(this.form);"/></div>
  </shiro:hasPermission>
	<shiro:hasPermission name="ext:guestbook_conf:edit">
  <div class="ls-btn"><input type="button" value="<s:message code="guestbookConf.setting"/>" onclick="location.href='../guestbook_conf/edit.do';"/></div>
  </shiro:hasPermission>
  <div style="clear:both"></div>
</div>
<table id="pagedTable" border="0" cellpadding="0" cellspacing="0" class="ls-tb margin-top5">
  <thead id="sortHead" pagesort="<c:out value='${page_sort[0]}' />" pagedir="${page_sort_dir[0]}" pageurl="list.do?page_sort={0}&page_sort_dir={1}&${searchstringnosort}">
  <tr class="ls_table_th">
    <th width="25"><input type="checkbox" onclick="Cms.check('ids',this.checked);"/></th>
    <th width="110"><s:message code="operate"/></th>
    <th class="ls-th-sort"><span class="ls-sort" pagesort="type.name"><s:message code="guestbook.type"/></span></th>
    <th class="ls-th-sort"><span class="ls-sort" pagesort="title"><s:message code="guestbook.title"/></span></th>
    <th class="ls-th-sort"><span class="ls-sort" pagesort="text"><s:message code="guestbook.text"/></span></th>
    <th class="ls-th-sort"><span class="ls-sort" pagesort="creationDate"><s:message code="guestbook.creationDate"/></span></th>
    <th class="ls-th-sort"><span class="ls-sort" pagesort="creationIp"><s:message code="guestbook.creationIp"/></span></th>
    <th class="ls-th-sort"><span class="ls-sort" pagesort="creationCountry"><s:message code="guestbook.creationCountry"/>(<s:message code="guestbook.creationArea"/>)</span></th>
    <th class="ls-th-sort"><span class="ls-sort" pagesort="reply"><s:message code="guestbook.reply"/></span></th>
    <th class="ls-th-sort"><span class="ls-sort" pagesort="status"><s:message code="guestbook.status"/></span></th>
    <th class="ls-th-sort"><span class="ls-sort" pagesort="recommend"><s:message code="guestbook.recommend"/></span></th>
  </tr>
  </thead>
  <tbody>
  <c:forEach var="bean" varStatus="status" items="${pagedList.content}">  
  <tr<shiro:hasPermission name="ext:guestbook:edit"> ondblclick="location.href=$('#edit_opt_${bean.id}').attr('href');" </shiro:hasPermission>>
    <td><input type="checkbox" name="ids" value="${bean.id}"/><f:hidden name="id" value="${bean.id}"/></td>
    <td align="center">
			<shiro:hasPermission name="ext:guestbook:copy">
      <a id="copy_opt_${bean.id}" href="create.do?id=${bean.id}&${searchstring}" class="ls-opt"><s:message code="copy"/></a>
      </shiro:hasPermission>
			<shiro:hasPermission name="ext:guestbook:edit">
      <a id="edit_opt_${bean.id}" href="edit.do?id=${bean.id}&position=${pagedList.number*pagedList.size+status.index}&${searchstring}" class="ls-opt"><s:message code="edit"/></a>
      </shiro:hasPermission>
			<shiro:hasPermission name="ext:guestbook:delete">
      <a href="delete.do?ids=${bean.id}&${searchstring}" onclick="return confirmDelete();" class="ls-opt"><s:message code="delete"/></a>
      </shiro:hasPermission>
     </td>
    <td><c:out value="${bean.type.name}"/></td> 
    <td><c:out value="${bean.title}"/></td>
    <td><c:out value="${bean.text}"/></td>
    <td><fmt:formatDate value="${bean.creationDate}" pattern="yyyy-MM-dd HH:mm:ss"/></td>
    <td><c:out value="${bean.creationIp}"/></td>
    <td><c:out value="${bean.creationCountry}"/><c:if test="${!empty bean.creationArea}">(<c:out value="${bean.creationArea}"/>)</c:if></td>
    <td><c:choose><c:when test="${bean.reply}"><s:message code="yes"/></c:when><c:otherwise><b><s:message code="no"/></b></c:otherwise></c:choose></td>
    <td><c:if test="${bean.status == 1}"><b></c:if><s:message code="guestbook.status.${bean.status}"/><c:if test="${bean.status == 1}"></b></c:if></td>
    <td><c:choose><c:when test="${bean.recommend}"><b><s:message code="yes"/></b></c:when><c:otherwise><s:message code="no"/></c:otherwise></c:choose></td> 
  </tr>
  </c:forEach>
  </tbody>
</table>
<c:if test="${fn:length(pagedList.content) le 0}"> 
<div class="ls-norecord margin-top5"><s:message code="recordNotFound"/></div>
</c:if>
</form>
<form action="list.do" method="get" class="ls-page">
	<tags:search_params excludePage="true"/>
 	<tags:pagination pagedList="${pagedList}"/>
</form>
</body>
</html>